services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: laravel-react-app
    container_name: laravel-react-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage:/var/www/storage
      - app-public:/var/www/public
    networks:
      - app-network

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: laravel-react-nginx
    container_name: laravel-react-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - app-public:/var/www/public
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel-react-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app-public:
    driver: local
 