<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        /**
         * Force HTTPS scheme in production environment.
         * 
         * When deploying with tunneling like cloudflare zero trust, activate this code to ensure
         * that all URLs generated by the application use the HTTPS scheme.
         */
        if ($this->app->environment('production')) {
            \URL::forceScheme('https');
        }
    }
}
